[[plugins]]
repo = 'reireias/vim-cheatsheet' 


[[plugins]]
repo = 'tlhr/anderson.vim'
[[plugins]]
repo = 'gosukiwi/vim-atom-dark'
[[plugins]]
repo = 'szorfein/fantasy.vim'
[[plugins]]
repo = 'nightsense/strawberry'
hook_add = '''
au MyAutoCmd VimEnter * nested call SetHighlightOptions()
function SetHighlightOptions()
  colorscheme strawberry-dark
  highlight Normal ctermbg=NONE guibg=NONE
  highlight NonText ctermbg=NONE guibg=NONE
  highlight LineNr ctermbg=NONE guibg=NONE
  highlight Folded ctermbg=NONE guibg=NONE
  highlight EndOfBuffer ctermbg=NONE guibg=NONE
endfunction
'''

